### ISSUE TITLE
8bitdo Gbros behaves differently to other 8bitdo controllers

### ISSUE THREAD

**Issue by vaderag** [darthcloud/BlueRetro#105]
I just got myself an 8bitdo Gbros GameCube to Bluetooth adapter and it seems to behave quite oddly
I'm actually connecting a GameCube pad to it and to GameCube and the mapping seems to be all over the shop. I was expecting that if I put it in switch mode it would be pretty seamless but everything seems off (even down to the analogue stick)
In X mode (windows) it's better but still a few buttons flipped - is there some way to align this to the other 8bitdo controllers so we can flip and change?

Also, I'm hoping to connect bongos using this and they seem to work but again mapping all over the shop, and not even sure where to begin mapping those 

Is there an easier way to handle switching controllers, as unless I'm missing something the settings are unified for the first input irrespective of what's connected?

**Comment by darthcloud** [comment]
Only use Xinput mode with 8bitdo controller in general. Their Switch support is broken and don't behave like a real Switch controller.

Also my Gbros is updated to latest 8bitdo FW v2.25.

Use the default gamepad mapping presets (Not the GC trigger merged preset).
In Xinput mode the L & R buttons expose both the analog and digital part.
