### ISSUE TITLE
Held buttons will randomly toggle state on the Atari Jaguar after FW 1.9.1

### ISSUE THREAD

**Issue by DoomyDoomer** [darthcloud/BlueRetro#1055]
### BlueRetro firmware version

24.04

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

Humble Bazooka

### System used

Atari Jaguar

### Bluetooth controller brand & name

Sony DualSense, 8BitDo SN30 Pro, Xbox Series X

### What is problem? (only list ONE problem per report)

Held buttons will toggle state randomly as if the user is lifting their fingers from the button. This issue started with Firmware 1.9.1.

### What did you expect to happen?

Held buttons should stay in the pressed state.

**Comment by darthcloud** [comment]
Fixed in v24.10 in theory by removing turbo feature for jaguar FW.

I'll rework that one day :)
