### ISSUE TITLE
PSX Porsche Challenge rumble not working on v24.10 other PSX titles ok

### ISSUE THREAD

**Issue by patters-match** [darthcloud/BlueRetro#1093]
### BlueRetro firmware version

24.10

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

PSUnoRetro (Willsconsolemodifications)

### System used

Sony PlayStation 2

### Bluetooth controller brand & name

Sony DualShock 4

### What is problem? (only list ONE problem per report)

I reported #155 long ago and you recently made changes to support dual motor rumble. I updated and tried it but strangely the rumble in PSX Porsche Challenge is not working, at least on PS2 via backwards compatibility (I don't have a real PSX to try). This works fine with a regular DualShock2, so if blueretro emulates this then it ought to work. I tried setting the system type from Auto to PS2 in the advanced config but that didn't help. Rumble support in Gran Turismo works fine for instance, so it may be some kind of edge case with this particular game.

### What did you expect to happen?

Rumble in game when the Analog mode is toggled for the controller.

**Comment by darthcloud** [comment]
What region of that game? I tried US one on a PS1 and no rumble on either OG analog, DS1 or DS2

**Comment by darthcloud** [comment]
Ok saw its was PAL in other bug, tried that and rumble does work. I'll check why BlueRetro doesn't work.

**Comment by darthcloud** [comment]
Work now with this build:
https://github.com/darthcloud/BlueRetro/actions/runs/11302189293

**Comment by patters-match** [comment]
Thanks, will try today. I should also have mentioned that the analog control worked fine.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by patters-match** [comment]
Woohoo - success! 😃  Thanks for the rapid response!
