### ISSUE TITLE
Can't turn on analogs

### ISSUE THREAD

**Issue by sjdr** [darthcloud/BlueRetro#151]
Use some strange android gamepad "flixpad" https://techbite.eu/gaming/flix-gamepad

And got a problem, pressing home on gamepad i cant turn on analogs.

On games that automaticaly turn on analogs like Crash Team Racing, analogs is working :)

Is there any way to create "analog mode on" by pressing two buttons like start + select ?

**Comment by darthcloud** [comment]
No you can't make button combo mapping in BlueRetro.

Ok so essentially your controller don't have any button that map to the home button by default.

Via the web interface https://blueretro.io/blueretro.html in mapping section select desc label PS2 and of the 32 first buttons that map to a blank button in destination change those to Analog. Save.

Now try to see if you controller home btn does the analog function or one of the other unused button do.
