### ISSUE TITLE
Getting Blueretro to work on ESP32-PICO-DevKitM-2

### ISSUE THREAD

**Issue by bixxewoscht** [darthcloud/BlueRetro#156]
Debug Log
[PICO Log.txt](https://github.com/darthcloud/BlueRetro/files/7972944/PICO.Log.txt)
:

**Comment by darthcloud** [comment]
Look like the Bare Metal hack for CPU1 make it crash.
Will look into it when I receive my devkit.

**Comment by bixxewoscht** [comment]
Thank you so much for your effort.
I just flashed it onto my devkit and will try it out once I have some free time.

The obvious pros of the Pico are that it enables even smaller builds, but the main question will be if you think the additional programming work is worth it.
I'll report back once I have some results.

**Comment by darthcloud** [comment]
No worries it's worth it for sure, I'll probably have official support in about a month.

**Comment by bixxewoscht** [comment]
I had some time to test this on N64 with the PICO Devkit today. Everything worked as it should, also changing the config and activating rumble. Looks good so far.

**Comment by bixxewoscht** [comment]
I had some time to test this on N64 with the PICO Devkit today. Everything worked as it should, also changing the config and activating rumble. Looks good so far.

**Comment by darthcloud** [comment]
let me handle issue closing ;)

**Comment by bixxewoscht** [comment]
Sorry, somehow GitHub did not let me comment without closing xD
