### ISSUE TITLE
PCE Controls

### ISSUE THREAD

**Issue by pmgducati** [darthcloud/BlueRetro#168]
Unlink the gamepad & GamePadAlt default mapping, so this way 2 btns mode will have I on right face, and II on bottom face, and select/III on left face.

https://github.com/darthcloud/BlueRetro/discussions/167

**Comment by darthcloud** [comment]
btw thanks a lot :) @pmgducati, v1.3 probably out by end of February.

**Comment by pmgducati** [comment]
Do you think this feature will be included in 1.4?

**Comment by darthcloud** [comment]
v1.3.1

**Comment by darthcloud** [comment]
See here my proposal for the new buttons mapping coming in v1.3.1

https://docs.google.com/spreadsheets/d/e/2PACX-1vT9rPK2__komCjELFpf0UYz0cMWwvhAXgAU7C9nnwtgEaivjsh0q0xeCEiZAMA-paMrneePV7IqdX48/pubhtml

Please review the PCE 2/3 btns & PCE 6 btns colums

**Comment by pmgducati** [comment]
I think it would be beneficial to have the I and II in their native spots (II = B/PAD_RB_RIGHT and I = A/PAD_RB_DOWN) as 99% of the game will be 2 buttons.  With that said I think III/Select could be either X/PAD_RB_LEFT or Y/PAD_RB_UP as users that are used to the original controllers would reach for select anyway, this is a new button that doesn't have a muscle memory for players.

**Comment by darthcloud** [comment]
If you check NES mapping B is RB_LEFT and A is RB down.

This is to match how SNES Mario world play vs the NES SMB, also technically when using a SNES pad on a NES Y is B and B is A.
To me this is more natural.

I know past that point in time the other way around became the prominent default but I really hate that personally.

So I'm not changing that, cause otherwise if you use 2 btns BT controller like Wiimote or Switch NES you end up missing a buttons.

**Comment by pmgducati** [comment]
Looking at the NES and the Wiimote in the I would still like to chat about the idea of using RB_RIGHT and RB_DOWN for PCE and NES.  This would make the Wiimote easier to play (I circled the current setup in Red and proposed in yellow).  This would also give the physical  layout to match the "Horizontal" buttons on the NES and TG-16/PCE controllers and Ladder back to the SNES B/A Layout. Let me know what you think.

![PXL_20220302_172441132 (1)](https://user-images.githubusercontent.com/20894227/156444424-9f780d18-b657-4b65-847d-14af11e4cdea.jpg)

**Comment by darthcloud** [comment]
Actualy Wiimote mapping is incorrect., right now, but it going to be change to 1 = L and 2 = D

I understand you point but ultimately my preference win ;) , I just prefer 2 btns games to use L and D on 4 btns ctrls.

**Comment by pmgducati** [comment]
Hey, I tried :) at least they will be on the face!  With all that said lets proceed!

**Comment by darthcloud** [comment]
Fixed in [v1.4](https://github.com/darthcloud/BlueRetro/releases/tag/v1.4)

**Comment by pmgducati** [comment]
Hey, Just got back from a vacation to this wonderful post!  I tested 1.4 and everything is working perfectly!  Thanks for everything!
