### ISSUE TITLE
Short rumble when switching between N64 controller pak and rumble pak

### ISSUE THREAD

**Issue by darthcloud** [darthcloud/BlueRetro#175]
### Discussed in https://github.com/darthcloud/BlueRetro/discussions/162

<div type='discussions-op-text'>

<sup>Originally posted by **StupidCoder** February 10, 2022</sup>
I'm using a PS5 Dual Sense controller with my N64, thanks to the amazing BlueRetro project. Thanks a lot for creating this! :)
I have only one slight problem with the setup: When using both the controller pak and rumble pak, it is hard to tell which one is currently active. When switching from controller pak to rumble pak, it would be great if the controller briefly rumbled as an indication.</div>

**Comment by mario-64** [comment]
How do you switch between rumble and memory pak? Mine is set to “both” but I can’t find any documentation on how to switch on the fly.

**Comment by darthcloud** [comment]
Docs is here:
https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-System-Specific-User-Manual#nintendo-64

Both is intended for Dreamcast.

At end of N64 docs the macro are listed.
You press the "Home" button to toggle between rumble and memory.

**Comment by mario-64** [comment]
> Docs is here: https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-System-Specific-User-Manual#nintendo-64
> 
> Both is intended for Dreamcast.
> 
> At end of N64 docs the macro are listed. You press the "Home" button to toggle between rumble and memory.
Thank you so much! Does the Home button require special mapping or just works by default?

**Comment by mario-64** [comment]
> Docs is here: https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-System-Specific-User-Manual#nintendo-64
> 
> Both is intended for Dreamcast.
> 
> At end of N64 docs the macro are listed. You press the "Home" button to toggle between rumble and memory.

Thank you so much! Does the Home button require special mapping or just works by default?

**Comment by taurus1101** [comment]
[mario-64](https://github.com/mario-64) You can't have the N64 set to both. I would set it to rumble and then use the home button to toggle as needed. The home button is mappable, but is a default button on the N64 Switch Controller.
