### ISSUE TITLE
Respuesta lenta en gamepad genérico y gamepad ipega 

### ISSUE THREAD

**Issue by LLETRAM** [darthcloud/BlueRetro#227]
I already did everything necessary in the tutorial I even bought two esp32 the first one never worked and the second one works but, I have to press the buttons very hard and sometimes it's like it won't press any buttons I am using ipega-9117 gamepad and a generic one for five dollars

**Comment by darthcloud** [comment]
You could flash the BlueRetro_pad_test.bin firmware and connect your ESP32 via USB on PC (do not connect to dreamcast) and get the log:
https://github.com/darthcloud/BlueRetro/wiki/Getting-BlueRetro-debug-logs-via-Serial-port-Windows-10

Copy log to txt file and attach here.

**Comment by darthcloud** [comment]
Reopen if you ever get the logs.
