### ISSUE TITLE
Wrone URL 

### ISSUE THREAD

**Issue by MaxJumper** [darthcloud/BlueRetro#233]
Hello!
Page https://blueretro.io/
[View on GitHub] (https://github.com/darthcloud/BlueRetroWebCfg)
You see **WebCfg**
Good URL is https://github.com/darthcloud/BlueRetro

**Comment by darthcloud** [comment]
The idea was to show the HTML source but I guess it's less confusing to link to main project repo.

URL updated

Thanks for suggestion!
