### ISSUE TITLE
xbox one controller malfunctioning on ps2

### ISSUE THREAD

**Issue by DonCristobal2021** [darthcloud/BlueRetro#235]
Good afternoon

I have a problem using an xbox one controller on the esp32 on the ps2, if I use a ps3 controller it works perfect, but the xbox one controller has problems, the buttons are uneven, some do not react, the only thing that works well is the cross

**Comment by darthcloud** [comment]
BlueRetro only support latest xbox Firmware, update with Update via the [Xbox accessories Win10 app](https://www.microsoft.com/en-us/p/xbox-accessories/9nblggh30xj3).

**Comment by DonCristobal2021** [comment]
Thank you very much, I will update, greetings friend good day.
