### ISSUE TITLE
Intermittent connection in N64 multiplayer games

### ISSUE THREAD

**Issue by DeathHorse1** [darthcloud/BlueRetro#236]
When I play Smash Bros and connect a wireless controller as player 1 and a cord N64 controller as player 2, the player 1 can't move the cursor correctly, this reset the position on second later.
The same issue occurs if I connect a wireless controller in other socket and the next controller has been connected by cord.

**Comment by darthcloud** [comment]
How are you setup? Are you connected externally using one port only?

**Comment by DeathHorse1** [comment]
I connected the ESP32 internally, for the 4 controllers. When I was playing Smash Bros, I played with a PS4 controller for the player 1, in the port 2, I connected a N64 cord controller for the player 2.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by darthcloud** [comment]
This not supported.

BTW this pure luck if it work for some people. Results may vary base on various factors.

My official stand is that you can't use BlueRetro with original controller simultaneously. You either need switch on ESP32 power or on individual data lines.
