### ISSUE TITLE
no n64 memory pak functionality with esp32s

### ISSUE THREAD

**Issue by delislej** [darthcloud/BlueRetro#238]
the blueretro for the n64 works for rumble and regular gameplay but the memory pak functionality seems to be broken. it is a hiletgo model from amazon. i've got a few 32e boards coming in from digi-key.

the error is:

Argh! RangeError: offset is out of bounds! on read or write of the mpk.

i have tried with v1.4 and v1.5 n64.

while this is probably an issue with the type of board i bought (32s), i just figured i'd open an issue.

**Comment by delislej** [comment]
ok, i missed the instructions about wiring the io26/27 to 3.3v. did that and it works. closing the issue!

**Comment by darthcloud** [comment]
Thanks for taking time to report what fixed it!

Enjoy!!
