### ISSUE TITLE
Recover MAC address in bluetooth

### ISSUE THREAD

**Issue by dragoncity17** [darthcloud/BlueRetro#249]
Hello,
Is it possible to recover MAC address in bluetooth ?
For after use with PS3 controller.

Or if not can you update your page "https://blueretro.io/", for have this information.

Thank you for everything because everything works perfectly !  :)

**Comment by darthcloud** [comment]
A workaround until I add this would be to look at the google chrome bt debug page on a desktop:

chrome://bluetooth-internals/#devices

click start scan and wait until BlueRetro show up in the list, make sure no controller is connected.

**Comment by darthcloud** [comment]
All page on web interface now display the MAC if FW v1.6 is used

**Comment by dragoncity17** [comment]
Great ! Good job :)
