### ISSUE TITLE
ESP32 ERROR

### ISSUE THREAD

**Issue by fermel01** [darthcloud/BlueRetro#250]
Hi
When connecting the esp32 module internally in a ps2 fat it turns on but does not link the controls.
Try externally and there if you link them
try the following diagram:
![diagram](https://user-images.githubusercontent.com/83359710/162840200-6ef54172-c0b4-485c-90f4-86d8799ec37c.png)

What can be?

**Comment by pmgducati** [comment]
You might have the same issue that I had, my ESP thought the PS2 was a PC-FX.  I was able to solve it by using the 3V3 pin vs the 5V. Apparently some PS2 have issues with either the 3V3 or the 5V/8V.

You can see my discussion here:
https://github.com/darthcloud/BlueRetro/discussions/234

Basically disconnect the 5V on the ESP/PS2 USB port and connect Pin 5 on the controller port to the 3V3 pin on the ESP32

![Untitled](https://user-images.githubusercontent.com/20894227/162843566-58f7763c-ea9f-435a-8b4c-35cf7c2fd290.png)
.
