### ISSUE TITLE
START Button on XB1 controller not working

### ISSUE THREAD

**Issue by bixxewoscht** [darthcloud/BlueRetro#262]
Note: I could not test this myself yet.

Several people told me that the Start button (3 lines) on the XBOX One controller does not work with the default mapping.

It is a quite common controller, so it would be able to use it without entering the web config first.

I'm sure many people would appreciate an update in a future release, if you have the time.

**Comment by darthcloud** [comment]
They just need to updated their controller to latest FW with the xbox
accessories app.

I only support latest xbox FW as noted on wiki:
https://github.com/darthcloud/BlueRetro/wiki/Controller-pairing-guide#xbox-one-s-series-xs--adaptive-controller

**Comment by darthcloud** [comment]
Reopen if FW update do not fix the issue.
