### ISSUE TITLE
Unable to pull BTRetro BT Mac from Serial Debugging

### ISSUE THREAD

**Issue by futurepr0n** [darthcloud/BlueRetro#267]
I was able to successfully connect to my BlueRetro via Bluetooth and bring up the advanced Config in a browser, and also followed the instructions to use serial connection to monitor what's going on and unfortunately it looks like I am just getting garbled text as response.

<img width="491" alt="Screen Shot 2022-05-02 at 12 29 47 PM" src="https://user-images.githubusercontent.com/478986/166273712-7d1eb509-8051-4fe3-8f39-5098efb4e832.png">

The goal for me is to pair a DualShock 3 to my PS2 - the steps to do this require using a DualShock Pairing utility on windows and also this intermediate step to get the BT Mac from debug. Unfortunately I am struggling to get that info.

<img width="868" alt="Screen Shot 2022-05-02 at 12 31 59 PM" src="https://user-images.githubusercontent.com/478986/166276778-c58a3322-6cf9-4072-b0b9-9332d291394d.png">

**Comment by futurepr0n** [comment]
I was able to pull my BT for it under edge:

<img width="904" alt="Screen Shot 2022-05-02 at 12 51 21 PM" src="https://user-images.githubusercontent.com/478986/166290464-b5205427-1da6-44b0-bcd9-03509302016e.png">


So that looked ok, except after using Sixaxis pair tool and changing the Mac - I cannot get the controller to pair when I start blueretro and the controller up. Is there something I am supposed to do to force pair?


I have a pulsing Blue LED, and solid Red LED

**Comment by darthcloud** [comment]
If you connect the controller back on PC and open Sixaxis pair tool again does the current master field show the correct MAC?

**Comment by futurepr0n** [comment]
thanks @darthcloud  - I actually had meant to close this issue last night - after more tinkering I believe the issue is my DS3's require a new battery. I think the Battery is so dead that it does not have the power to connect. The pairing is showing that they managed to update what device its paired to. I am waiting on some replacement batteries. Appreciate your help, and thank you for working on such an amazing project!
