### ISSUE TITLE
3do receiver does not work on the goldstar model

### ISSUE THREAD

**Issue by scp-electrocution** [darthcloud/BlueRetro#269]
I am testing the receiver on a 3do goldstar, the led lights up but the ps4 controller does not pair while on the fz-1 it works perfectly.

**Comment by darthcloud** [comment]
If you press EN button on ESP32 after power up does it work?

You could also try to disconnect the 5v from console, and power it via usb.

If none of those work, maybe goldstar one don't have 200mA available at the front port.

**Comment by scp-electrocution** [comment]
Pressing the EN key solved the problem, also tested on other 3do models

**Comment by darthcloud** [comment]
Get a DS1233A-10+T&R PMIC supervisor and wire it on the EN pin, this will delay esp power up by holding EN 250ms. Also had a 1uF cap & 100uF cap between 3V3 and GND pin of ESP.

See transistor on the back of ESP, this is the PMIC.
![PXL_20220507_120916349](https://user-images.githubusercontent.com/3744056/168037593-a8fdea4e-9985-424d-b2a7-bb763b8253c4.jpg)

**Comment by darthcloud** [comment]
Feel free to reopen if using PMIC do not solve it.
