### ISSUE TITLE
SW_RESET loop on install v1.6.1 with Wemos Lolin32

### ISSUE THREAD

**Issue by gantich** [darthcloud/BlueRetro#292]
Trying to install v1.6.1 on a Wemos Lolin32 V1.0.0 with a ESP-WROOM-32. Is this board supported?

`Detecting chip type... ESP32
Chip is ESP32-D0WDQ6 (revision 0)
Features: WiFi, BT, Dual Core, Coding Scheme None
Crystal is 40MHz
MAC: ...
`

On running the upload command with:

`esptool.py -p /dev/cu.SLAB_USBtoUART    \
  -b 460800 --before default_reset --after hard_reset --chip esp32 \
  write_flash --flash_mode dio --flash_size detect --flash_freq 40m \
  0x1000 bootloader/bootloader.bin \
  0x8000 partition_table/partition-table.bin \
  0x10000 BlueRetro_gc_external.bin 
`

The output is:

`
esptool.py v3.3.1
Serial port /dev/cu.SLAB_USBtoUART
Connecting....
Chip is ESP32-D0WDQ6 (revision 0)
Features: WiFi, BT, Dual Core, Coding Scheme None
Crystal is 40MHz
MAC: 30:ae:a4:04:4b:ac
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x00001000 to 0x00006fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x00010000 to 0x00094fff...
Compressed 23104 bytes to 14675...
Wrote 23104 bytes (14675 compressed) at 0x00001000 in 0.7 seconds (effective 262.9 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 153...
Wrote 3072 bytes (153 compressed) at 0x00008000 in 0.1 seconds (effective 267.0 kbit/s)...
Hash of data verified.
Compressed 540768 bytes to 329787...
Wrote 540768 bytes (329787 compressed) at 0x00010000 in 9.0 seconds (effective 479.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
`

Wich seems to have been correctly uploaded but on monitoring serial port i get this loop

`rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:5464
load:0x40078000,len:14280
load:0x40080400,len:3268
entry 0x40080608
⸮5⸮⸮!r⸮⸮J⸮!q⸮⸮ets Jun  8 2016 00:22:57
`

I have tried to erase flash before uploading
`esptool.py --chip esp32 --port /dev/cu.usbserial-014C16CE erase_flash`

**Comment by darthcloud** [comment]
In theory yeah but this one clearly got extra hardware interfering.

Officially I only support espressif ESP32-DEVKITC-32E as listed in the BOM
https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-DIY-Build-Instructions#bill-of-materials
