### ISSUE TITLE
N64 & GC broken for some in v1.6

### ISSUE THREAD

**Issue by Valkristh** [darthcloud/BlueRetro#310]
Hello, first thanks for the continuous work!

I have installed blueretro in my Wii internally to the 4 gcn ports, the first firmware was 1.2.2 (gc spiffs) everything working fine, but i updated to 1.6.1 (gc spiffs) and as the title says all the BT controllers stopped working for some reason idk.
My question is, can i go back or downgrade to 1.2.2 without problems? If the answer is yes I'm gonna try other releases after that one

**Comment by darthcloud** [comment]
You can downgrade no problem,

Probably 1.6 broke it? Try 1.6 to confirm that it fail too, try 1.5.1 that one should be fine.

**Comment by Valkristh** [comment]
Ok thanks, here is my report
As you said 1.6 broke it and 1.5.1 worked fine

**Comment by darthcloud** [comment]
Ok so the fix for #264 likely at fault here

**Comment by darthcloud** [comment]
Not sure why but new FW push-pull output doesn't work when there is a small resistance in line ~100ohm

Double check your soldering of the data pin to make sure its not a cold joint. Maybe take a picture too so I can see.

**Comment by Valkristh** [comment]
> Not sure why but new FW push-pull output doesn't work when there is a small resistance in line ~100ohm
> 
> Double check your soldering of the data pin to make sure its not a cold joint. Maybe take a picture too so I can see.

Okay I'm gonna take a pic, but (in wii) i remember that there are some components too far (at least 1cm) for a cold joint

**Comment by Valkristh** [comment]
![20220624_100950](https://user-images.githubusercontent.com/24465772/175553731-3645708d-3acc-4bcd-bf77-de3b2d6d8711.jpg)

From right to left: gnd, data1, Vin, data 2, data 3, data 4

**Comment by darthcloud** [comment]
v1.6.3 should fix this:

https://github.com/darthcloud/BlueRetro/releases/tag/v1.6.3
