### ISSUE TITLE
Retro Bit Mega Drive bluetooth not working

### ISSUE THREAD

**Issue by micropixel70** [darthcloud/BlueRetro#312]
I tried a Retrobit Bluetooth brand gamepad for megadrive, but it doesn't work, is there any way to make it work?  thank you

**Comment by delislej** [comment]
can we see a picture of your wiring for the ESP32? it's very hard to diagnose anything without it.

**Comment by micropixel70** [comment]
> can we see a picture of your wiring for the ESP32? it's very hard to diagnose anything without it.

I don't have the ability to do this, do you know if this brand in bluetooth turns out to work?  thank you

**Comment by micropixel70** [comment]
> I ordered the Saturn one, so hopefully it's the same thing and it will get fixed at the same time.

Thanks, I await news💪🏻🙂

**Comment by darthcloud** [comment]
See https://github.com/darthcloud/BlueRetro/wiki/Controller-pairing-guide#retro-bit on how to pair controller.

Only XInput mode is supported (Home + X)
