### ISSUE TITLE
[PC-FX] Random press in Zeroigar

### ISSUE THREAD

**Issue by darthcloud** [darthcloud/BlueRetro#323]
Random press in Zeroigar

**Comment by darthcloud** [comment]
Test build.

This inverted the clock line like the latch and data. This might help keeping the signals in sync within the GPIO matrix.
Switched from SPI mode 0 non-DMA timing to mode 2 DMA ones.

Reduced the SPI setup time to minimum when latch interrupt

[v1.8.4-35-g8fbc9d5_hw1_pcfx.zip](https://github.com/darthcloud/BlueRetro/files/12853208/v1.8.4-35-g8fbc9d5_hw1_pcfx.zip)

**Comment by DoomyDoomer** [comment]
This appears to have fixed the issue. I'm going to have it tested further by my tester but seems to work. This also fixed an issue with Team Innocent I was seeing with the character run movement stopping randomly.

**Comment by darthcloud** [comment]
Fixed in v1.9 https://github.com/darthcloud/BlueRetro/releases/tag/v1.9
