### ISSUE TITLE
My esp32 sometimes does not react to the keys of my original ps3 controller

### ISSUE THREAD

**Issue by DonCristobal2021** [darthcloud/BlueRetro#342]
Buenas tardes

Friend I have a problem I hope you can help me please, I am playing esp32 on a ps2 slim externally with an original ps3 controller, when I turn on the console the esp32 turns on and my controller synchronizes but does not react to any key, then I turn off the console I turn it on again and now everything works fine, it may be that it has a false cable since I moved the cables.

**Comment by DJm00n** [comment]
May be related to #250
