### ISSUE TITLE
Feature request: Wavebird support

### ISSUE THREAD

**Issue by 5p4rkP1ug** [darthcloud/BlueRetro#368]
There's plenty of GameCube Wavebird controllers for sale on various websites, however, a number of them don't come with the required receiver. This makes them undesirable to most people. 

I know Wavebird controllers don't use the Bluetooth protocol, but it's a wonderful device that I'd love to be able to use on multiple devices, as well as a GameCube of course.

**Comment by darthcloud** [comment]
Simply impossible in the context of this project.
