### ISSUE TITLE
[Request feature] Soft reset pressing a button or combinate buttons

### ISSUE THREAD

**Issue by rpf16rj** [darthcloud/BlueRetro#373]
Hi, is possible implement a feature to when press a combinate buttons, put two pins GPIO in short for a quick time to be use a soft reset button in some consoles like N64, SNES, Sega genesis, Sega Dreamcast? 
This case is for board esp inside the sonsole solded direct. 
In Sega Dreamcast for exmample, with Dreamshell, for very times the console freezes and to recovery need a turn off and turn on, but exist a way to soft reset, like see here: http://dcevolution.sourceforge.net/dchelp/DreamcastResetbutton.pdf

N64, SNES, Genesis have reset buttons like push native and wold be amazing if can possible in bluetooth controll.

**Comment by darthcloud** [comment]
Wait for v1.8 for internal install support and instructions
