### ISSUE TITLE
start not working on ps1

### ISSUE THREAD

**Issue by Radeon91** [darthcloud/BlueRetro#376]
finally got an esp32 working and flashed with psx 1.7.3 but just notice that the start button isn't working, i have paired and xbox one s controller and must be the menu button but it does nothing

**Comment by Radeon91** [comment]
Tried to change buttons via mapping but still dopesnt work.

**Comment by darthcloud** [comment]
You need to update xbox controller FW to latest with xbox accessories app for win 10
