### ISSUE TITLE
Blueretro unreliable with multiple controllers on N64

### ISSUE THREAD

**Issue by netham45** [darthcloud/BlueRetro#378]
I'm having issues getting multiple N64 NSO controllers to work reliably with my BlueRetro on an N64. I have all four controllers connected to the N64. I'm using an ESP-WROOM-32 development board ( https://www.amazon.com/dp/B08246MCL5 ) . I have also tried https://www.sparkfun.com/products/13907 and was having a similar issue, though I didn't capture logs from that one.

One or two controllers seem to work, but once I connect all four I'll randomly have controllers drop out. I've never had all four working for more than 30 seconds or so.

https://pastebin.com/ntN9Z6sW

I'm having the issues across multiple games. I'm using an EverDrive 64 x7.

**Comment by darthcloud** [comment]
This is a know issue see: issue #146 

Closing as duplicate
