### ISSUE TITLE
IGR Mod

### ISSUE THREAD

**Issue by maniaco007** [darthcloud/BlueRetro#397]
Would it be possible to use the board for the IGR Mod on Playstation 1?

Would it be possible to have this functionality through ESP32?

**Comment by darthcloud** [comment]
This is coming in next veraion v1.8 in about a month.

**Comment by maniaco007** [comment]
> This is coming in next version v1.8 in about a month.

looking forward to it... do you have a forecast of when you will publish?

**Comment by maniaco007** [comment]
Has In Game Reset been implemented?
