### ISSUE TITLE
GameCube controllers stuck

### ISSUE THREAD

**Issue by Moadib6** [darthcloud/BlueRetro#400]
When I'm playing GameCube at some point, the controller stays on and stuck, like on standby. but the controller does not react and I have to turn off the console to make it work again.

I use an xbox one controller and a ps4 controller, with both controllers this error occurs.

**Comment by Moadib6** [comment]
- I turn on my gamecube
- sync PS4/XBOX-ONE controller
- start a gamecube game
- at the moment when I'm playing the game, the PS4/XBOX-ONE controller gets stuck, it's not always like that
- I have noticed that it happens when you have to press many buttons at the same time for long periods
- the control does not turn off it just stops responding and does not let you do anything else
- I solve it, I turn off the gamecube, turn it back on and sync the controller and everything works fine

**Comment by darthcloud** [comment]
No my question is how you installed your blueretro. Take picture of the esp32 where I can see all connection easily.

**Comment by Moadib6** [comment]
These are the pictures of the installation
![WIN_20220923_22_29_05_Pro](https://user-images.githubusercontent.com/90208317/192078243-6881e267-b581-41ca-bf0b-bb53d9ad6156.jpg)
![WIN_20220923_22_29_44_Pro](https://user-images.githubusercontent.com/90208317/192078252-c0419348-4b96-41ab-a8ed-1b6dcf199cf2.jpg)
![WIN_20220923_22_29_56_Pro](https://user-images.githubusercontent.com/90208317/192078261-3684c1d1-34db-42ad-b4c4-64007d5564e1.jpg)
this is the diagram i made
![blue gc](https://user-images.githubusercontent.com/90208317/192078291-a63335c2-8b29-4400-8daf-a39c8aa67d4b.png)

**Comment by darthcloud** [comment]
Leaving the ESP32 in static generating foam is rally bad.

This is not an official espressif board and people often got issue with those.

Try getting an official one from digikey or mouser.
ESP32-DEVKITC-32E with ESP-WROOM-32 (Get it on [Digikey](https://www.digikey.com/en/products/detail/espressif-systems/ESP32-DEVKITC-32E/12091810?s=N4IgTCBcDaIKYGcAOBmMBaAJnAbgawEsAXAY3TThAF0BfIA) or [Mouser](https://www.mouser.com/ProductDetail/Espressif-Systems/ESP32-DevKitC-32E?qs=sGAEpiMZZMv0NwlthflBi3XYxq%252BTapwyHnR2%2FrAf4bY%3D))

**Comment by Moadib6** [comment]
Thanks for the help, I'll remove the sponge and get an official esp32

**Comment by krikris** [comment]
Source of the diagram: https://www.mundoyakara.com/2022/02/controles-bluetooth-en-nintendo.html

**Comment by Moadib6** [comment]
ok, i will follow this diagram
