### ISSUE TITLE
Wrong links on "Controller pairing guide" Wiki page

### ISSUE THREAD

**Issue by DJm00n** [darthcloud/BlueRetro#413]
On [this page](https://github.com/darthcloud/BlueRetro/wiki/Controller-pairing-guide): `8bitdo Win10 app` should link to https://apps.microsoft.com/store/detail/8bitdo-ultimate-software/9PMC9MN3ZZ85
Also you can update `Xbox accessories Win10 app` link to https://apps.microsoft.com/store/detail/xbox-accessories/9NBLGGH30XJ3 for consistency.

**Comment by darthcloud** [comment]
Thanks for reporting. Links updated!
