### ISSUE TITLE
Doesnt work on PS3 console

### ISSUE THREAD

**Issue by Ntemis** [darthcloud/BlueRetro#414]
I connected blueretro through usb to the PS3 console and paired my PS4 controller but i was not able to navigate the menu with the pads or the analog sticks , i even rebooted the ps3 console plugged and unplugged the usb cable just to be sure.
Does blueretro work with the ps3 console?

**Comment by darthcloud** [comment]
ESP32 got no USB port, its just a USB serial IC.

BlueRetro has no usb capabilities.

**Comment by Ntemis** [comment]
So we cannot use it on a ps3 console? Is there any adapter i can make or something?

**Comment by Raphfriend** [comment]
No, it won't work with any USB device.
