### ISSUE TITLE
[FR] USB HID wired connectivity option

### ISSUE THREAD

**Issue by eadmaster** [darthcloud/BlueRetro#42]
USB HID wired connectivity usually provides lower latency than BT and better compatibility on some platforms.

Possible solutions:
 1. use another uC to handle the USB HID communication (e.g. an Arduino Micro), connected via serial to the ESP32
 2. use the ESP32S2 + [TinyUSB library](https://github.com/hathach/tinyusb) (or [this](https://github.com/chegewara/EspTinyUSB)?)
3. via software-only USB on regular I/O pins (i've only found an [ESP8266 lib  for this](https://github.com/cnlohr/espusb))

**Comment by darthcloud** [comment]
This project is about Bluetooth. Sorry no USB input.
