### ISSUE TITLE
DC additional lag with rumble and disconnects

### ISSUE THREAD

**Issue by Pabletex91** [darthcloud/BlueRetro#430]
Hi! I'm using the 1.7.3 version and works flawless on my dreamcast unless i turn on the rumble. It starts to lag but only in some racing games (i'm currently plaging Tokyo Xtreme Racing 2) and sometimes disconnects my controller.  Also I already adjust the deadzone to the maximum value (0.0255) and still very sensitive in the middle (things like 240p test and Resident Evil 2 moves itself when my Xbox series/PS3 controllers shows 0.00 in Windows) Finally i want to know when will the vmu feature be available. Thanks in advance!

**Comment by darthcloud** [comment]
Rumble for DC is not properly implemented, this will be fixed in the future in the context of #5 

Best to leave it off.
