### ISSUE TITLE
(PS1) Analog button doesn't work to switch between d-pad and left joystick

### ISSUE THREAD

**Issue by vcesne** [darthcloud/BlueRetro#456]
Hello,

Analog button doesn't work to switch between d-pad and left joystick.
Tested with PS4 and Xbox serie controller.

**Comment by darthcloud** [comment]
Can you provide more details? It work for me.

Which game?
Which buttons you press on PS4 and xbox controller?

**Comment by vcesne** [comment]
It happened with Tony Hawk 2 and Ridge Racer Type 4.

I pressed Xbox button and PS button to switch between d-pad and left joystick without success.

I have the same problem with a Psone and a PS1.

**Comment by Invictaz** [comment]
Interesting find, need to hear more about this.

**Comment by darthcloud** [comment]
@Invictaz dont spam bug tracker with useless comments

**Comment by darthcloud** [comment]
The Xbox Home button used to be a bit bogus in older version but in recent BlueRetro FW like v1.9.2 used in conjunction to latest Xbox controller firmware from the [Xbox accessories Win10 app](https://apps.microsoft.com/store/detail/xbox-accessories/9NBLGGH30XJ3) I think that should be fine now.

If not feel free to reopen the issue.
