### ISSUE TITLE
ps4 joystick not connecting

### ISSUE THREAD

**Issue by jairslira** [darthcloud/BlueRetro#459]
my ps4 joystick does not connect, it works normally both on the ps4 console and on the pc, but not on the blueretro, I have already reset the joystick and the blueretro has the latest firmware version, I want to know if someone can help me, thank you in advance for your attention

**Comment by cermeza** [comment]
In blue retro you have six axis tool for ps3 joystic work for ps4 but if you long press pair buton wait until blinking then pres share and pslogo on controler and hold until  light bar start flashing fast it will conect fast I haved same problem with manual on blue retro
Regards

**Comment by darthcloud** [comment]
@jairslira what model of PS4 controller you got? Original from Sony? What model number?

**Comment by jairslira** [comment]
Hello, I saw that the problem was actually with the control itself, which
was defective, thanks for your attention

Jacques Gagnon ***@***.***> escreveu (sábado, 20/04/2024 à(s)
17:34):

**Comment by darthcloud** [comment]
No worries, thanks for the update
