### ISSUE TITLE
Support for flydigi Apex 3

### ISSUE THREAD

**Issue by hardlevel** [darthcloud/BlueRetro#470]
Hi!
I tryed to use Apex 3 with blueretro, but could only use it on IOS mode.

The mapping is messed up, I tryed to remap using the web interface but without success, some buttons are not recognized.

Any chances to make blueretro support it?

**Comment by darthcloud** [comment]
Get me a trace of it see:
https://github.com/darthcloud/BlueRetro/wiki/Bluetooth-HCI-trace-with-Win10

**Comment by hardlevel** [comment]
Yes, I saw that in documentation... I have a lot of controllers that can be
add :)

Em qua., 18 de jan. de 2023 às 09:23, Jacques Gagnon <
***@***.***> escreveu:

**Comment by darthcloud** [comment]
No trace provided, feel free to reopen with one.
