### ISSUE TITLE
Dualsense simulated click for Gamecube

### ISSUE THREAD

**Issue by coolbho3k** [darthcloud/BlueRetro#483]
I've seen this requested a few times. It would be great to have an option on the Dualsense to simulate the tactile bump at the end of the L/R button travel for Gamecube controllers.

I want to look into this myself - the only hardware I have is the Laser Bear internal PCB which is coming today, as long as I am able to figure out how to compile for/flash it I'm good to do some experimentation.

**Comment by coolbho3k** [comment]
`bt_hidp_ps5_set_conf` is I think analogous to the `outputReport` data structure in DS4Windows: https://github.com/Ryochan7/DS4Windows/blob/master/DS4Windows/DS4Library/InputDevices/DualSenseDevice.cs

So we must write to a bunch of the bytes in `tbd1` to set trigger effects.

**Comment by coolbho3k** [comment]
I got my ESP32 dev boards in earlier this week, and I'll look into it over the holiday. Thanks!!!

**Comment by Invictaz** [comment]
@coolbho3k any updates?

**Comment by coolbho3k** [comment]
I didn’t have time to play around this over holidays, but planning on
getting to this soon!

**Comment by coolbho3k** [comment]
Sorry for late update. I finally got time to work on this and got this working. I'll have a PR later this week.

**Comment by coolbho3k** [comment]
See https://github.com/darthcloud/BlueRetro/pull/640 for a preliminary version of this. I'd like feedback on how we'd configure this. 

I haven't tested on my actual GameCube yet, but I can feel the trigger click with my bare ESP32.

**Comment by Invictaz** [comment]
Isnt it so that in the GameCube games the effect only works on the left or right trigger?

**Comment by coolbho3k** [comment]
@Invictaz My intention was to simulate the digital "click" at the bottom of the travel on original GameCube controllers. It's on both the L and R trigger on the GameCube.

**Comment by Invictaz** [comment]
Yeah but I know of some controversy around the Super Mario Sunshine game that the click was needed and some emulators or controllers did not operate it well enough.

**Comment by coolbho3k** [comment]
OK, I think the PR is mostly working now.
