### ISSUE TITLE
Tons of visual analog noise after connecting BlueRetro in GameCube 

### ISSUE THREAD

**Issue by Mitch200584** [darthcloud/BlueRetro#494]
It used to be crystal clear, but now there is a layer of subtle static all over the screen. Most noticeable on GameBoy Interface HF when using a Flashcart on the blue homescreen. I use EZ Omega Definitive Edition.

**Comment by darthcloud** [comment]
Sound like possibly a power related issue.

Which type of GameCube you got? DOL-001 or DOL-101?

Are you using an official Nintendo power supply? (DOL-002)

**Comment by darthcloud** [comment]
Just to confirm, I assume RGB scart cable means you got a PAL cube with RGB on the analog port? (So no video mods)

**Comment by Mitch200584** [comment]
I have a NTSC GameCube. It supports RGB if it has the serial port

**Comment by Mitch200584** [comment]
I forgot to mention the GCHD MKII. Thats how I plug my Scart cable into it

**Comment by Mitch200584** [comment]
Words From Mike Chi (RetroTink5X):  
"The EON device is inherently noisy. My guess is it’s picking up whatever extra noise is being generated. Obviously in an ideal world the blue retro won’t be generating noise, & if it did, the EON would be designed properly to filter it. But these things happen."

So I don't know this firmware fixable or maybe a future revision could tackle this, but yeah, unfortunate for EON/RGB Scart users. I really did like the Console reset feature :P

**Comment by darthcloud** [comment]
For sure I can do much about that software wise, might be best to contact laser bear directly as they designed the hardware.

**Comment by Extrems** [comment]
I couldn't measure a difference before and after installation of the GameCube BlueRetro Internal Adapter using the FFT function of my Siglent SDS1104X-E (200 MHz unlocked), with the EON GCHD Mk-II Rev 1, HD Retrovision Wii Component Cable, RGBench, and a Wii U Pro Controller connected. The normal spikes at 54 MHz and above can be observed, but nothing new and even less so within nominal video bandwidth.

I couldn't notice a difference on the RetroTINK-5X Pro either.

**Comment by Extrems** [comment]
I've done more measurements using the Bitfunx GameCube Component Cable, Retro-Bit Retro Prism Component Cable, and the Nintendo GameCube Component Video Cable. I'm now pretty confident this is not a design flaw of the GameCube BlueRetro Internal Adapter.

**Comment by darthcloud** [comment]
Thanks for the test result.

Likely something specific to that console.

Can't do much myself about this so closing.
