### ISSUE TITLE
No compatibility with PS2 accessories?

### ISSUE THREAD

**Issue by fermel01** [darthcloud/BlueRetro#495]
Good day,
I wanted to know if there is a possibility that an internal ESP32 interferes with the official PS2 DVD receiver?... since when it is connected to the second control bay it stays in standby, is this correct or do I have some other problem?

I look forward to your comments, thank you very much!
![control](https://user-images.githubusercontent.com/83359710/207645639-351293b3-7a79-4ba2-a1f3-2ae9e4094b03.png)

**Comment by darthcloud** [comment]
All legacy BlueRetro FW (named HW1 going forward) interfere with external wired device. Internal install is simply an unsupported use case. If you do so you loose the ability to use the wired port unless you use some way to disconnect blueretro or turn it off.

HW2 based install install is the proper way https://github.com/darthcloud/BlueRetro/wiki#2---building-hardware-hw2

But note that I do not provide instruction on how to do so, the HW2 FW as the capability but you got to figure out how to install yourself.
