### ISSUE TITLE
GameCube FW1.8 laggy Switch controllers 

### ISSUE THREAD

**Issue by Arial-Bold** [darthcloud/BlueRetro#504]
I have the current 1.8 firmware for the GameCube blue retro board and when only using one of the PowerA GameCube switch controllers everything works perfectly fine. When another switch controller is connected to second, third, or fourth player those additional controllers are excessively laggy if not completely unusable due to the lag. Also from time to time the connection of one or the other multiple connected switch controllers will drop its connection and need a full reset to reconnect. @darthcloud is there any plan to fix this issue in a future update? It is really hard to believe that the only Bluetooth controller which emulates the look and feel of an original GameCube controller hasn't been thoroughly tested and a workaround made for this yet.

**Comment by darthcloud** [comment]
This known issue see #146 

No fix found yet.
