### ISSUE TITLE
My ESP32-DEVKITC-32E wouldn't flash on Windows, so heres what I did

### ISSUE THREAD

**Issue by Sowden** [darthcloud/BlueRetro#508]
Hey guys.  I had some trouble getting my ESP32-DEVKITC-32E to flash the latest firmware.  I read the tutorials, followed videos online, it would only stay stuck on "Sync"  So I opened up my Device Manager to try to investigate if it was a COM port issue.  I plugged and unpluged it to notice that there was no newly added COM port.  Then I noticed that the SDP32 windows drivers weren't installing properly (because of course it won't).  So I did some searching, and I found a site that had proper CP210x windows drivers.  You can find the link below:

https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads

Installed the drivers and a new COM port showed up.  Did the flash and it went as it should.  If this is a common problem, maybe this info should be added to the Windows 10 wiki page?  Just wanted to share in case it might help anyone else.  Thanks.

**Comment by darthcloud** [comment]
I added a link to the official espressif docs which got link to the same driver:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/establish-serial-connection.html

This way it will stay up to date.

Thanks for reporting!
