### ISSUE TITLE
BlueRetro 1.8.1 N64- Accessory type "Both" breaks Rumble and Memory pack functionality

### ISSUE THREAD

**Issue by wtfbbqhax** [darthcloud/BlueRetro#511]
After upgrading the firmware to 1.8.1 I started seeing games report corrupt memory pack. I continued testing and found Rumble was also not working.

I've narrowed this down to the Accessory type "Both" and have attached a video as well. 

This was working correctly using the previous firmware. 

https://user-images.githubusercontent.com/7323455/209241560-5619aa19-da60-45d2-bee1-7dee72dc2944.MOV

**Comment by darthcloud** [comment]
Dont use both, n64 is not a dreamcast it got only one slot, set either none, rumble or mem.

Docs define valid value for N64
https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-System-Specific-User-Manual#accessories-14

**Comment by wtfbbqhax** [comment]
Ack, thanks for that
