### ISSUE TITLE
Not being able to update the firmware correctly

### ISSUE THREAD

**Issue by fermel01** [darthcloud/BlueRetro#524]
Hi good day;
I don't understand what I'm doing wrong, it's my third time updating the Blueretro and it's the first time it's happened to me, I want to update its firmware from version 1.7.3 to the latest version 1.8.1 but it won't let me, what could I be doing wrong ?... my installation is internal with an ESP32 on the PS2 console.

Thanks for your support
![error ps2](https://user-images.githubusercontent.com/83359710/210097113-97e2f714-fa3f-40c1-8834-39d83864ddc2.png)

**Comment by darthcloud** [comment]
Dod you use the FW coming from the HW1 archive?

**Comment by fermel01** [comment]
No, the v1.8.1_hw2 was downloaded

**Comment by darthcloud** [comment]
Download the hw1 one 😛
