### ISSUE TITLE
After install the blueretro on gamecube

### ISSUE THREAD

**Issue by yozan2450** [darthcloud/BlueRetro#529]
so i just installed the blue retro bluetooth and when i push the power button it lights up blue and doesn't turn on but the fan is spinning non stop. i also have a pico installed and a sd card in the bottom port of the gamecube. how do i fix this?

**Comment by hugo-brito** [comment]
Try and press the reset button. This issue is documented on the GameCube board page in laser bear industries.

**Comment by darthcloud** [comment]
@yozan2450 You should contact Laser Bear support https://www.laserbear.net/pages/contact-us

This look like an installation issue.

**Comment by yozan2450** [comment]
Yea the ribbon cable had a defect in it
