### ISSUE TITLE
[BT] Add ESP32-BLE-Gamepad as BT_HID_GENERIC support and SELECT, START, L2, R2, MAPPING

### ISSUE THREAD

**Issue by yakaracolombia** [darthcloud/BlueRetro#531]
please add a default id "BleGamepad" form ESP32-BLE-Gamepad

none of the 128 buttons form the ESP32-BLE-Gamepadm library is mapped for SELECT, START, L2, R2, MAPPING

can you enable the START and SELECT from special button list in [BleGamepadConfiguration.h](https://github.com/lemmingDev/ESP32-BLE-Gamepad/blob/master/BleGamepadConfiguration.h)

PAD_MS   =  SELECT_BUTTON
PAD_MM   =  START_BUTTON

OR enable as typical android/windows mapping 

PAD_MS  =  BUTTON_9 0x9
PAD_MM  = BUTTON_12 0xc
PAD_LM  =  BUTTON_25 0x19
PAD_RM = BUTTON_26 0x1a

**Comment by darthcloud** [comment]
Many people used that project to make controller and they didn't need to make any change to BlueRetro.

You need to edit the ESP32-BLE-Gamepad so that the button endup where BlueRetro expect them.

See this thread:
https://github.com/darthcloud/BlueRetro/discussions/311
