### ISSUE TITLE
Issue Laserbear Adapter Xbox one Controller 

### ISSUE THREAD

**Issue by Nykalthir** [darthcloud/BlueRetro#534]
Hello!
I have a Issue with configuring a Xbox one Controller for my Gamecube with the Laserbear Adapter.
I can't configure it properly, the Buttons seams to not match with the Text in the advanced section.
I also tried it with a Xbox Series S/X Controller and it worked fine.
I used the latest Firmware 1.8.1

Regards (:

**Comment by darthcloud** [comment]
Update your Xbox controller with the Xbox accessories app:
https://apps.microsoft.com/store/detail/xbox-accessories/9NBLGGH30XJ3

**Comment by Nykalthir** [comment]
Thanks for the fast answer, that solved the problem, thank you so much, you are awesome (:
