### ISSUE TITLE
8bitDo Saturn DIY controller captures

### ISSUE THREAD

**Issue by svirant** [darthcloud/BlueRetro#536]
The "8bitDo Saturn DIY" controller has 4 different controllers modes. I have captured
each one in their respective modes.  Below is the order of buttons pressed:

UP
DOWN
LEFT
RIGHT
A
B
C
X
Y
Z
Start
L
R

[8bitDo-Saturn-DIY.zip](https://github.com/darthcloud/BlueRetro/files/10402901/8bitDo-Saturn-DIY.zip)

**Comment by darthcloud** [comment]
Awesome thanks!

**Comment by darthcloud** [comment]
v1.8.2 now support this controller natively. https://github.com/darthcloud/BlueRetro/releases/tag/v1.8.2

The controller need to be configured to expose the d-pad as a d-pad:
https://github.com/darthcloud/BlueRetro/wiki/Controller-pairing-guide#73---d-pad-as-joystick-or-d-pad-configuration
