### ISSUE TITLE
[Wired] Add Wii extension support for encryption mode

### ISSUE THREAD

**Issue by darthcloud** [darthcloud/BlueRetro#545]
Would need to integrate Marcan code https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/HW/WiimoteEmu/Encryption.cpp

But it's GPL and not willing to change the project license.

Could ask Marcan if possible to dual license the code.

**Comment by Invictaz** [comment]
Implementation is here
http://web.archive.org/web/20111210161944/http://pastie.org/private/6vajs4t1glpd2fome7x1g

Writeup here

**Comment by darthcloud** [comment]
Marcan is ok with licensing his code under MIT, so that might come in future if the impact on resources usage is acceptable.

![Screenshot_20230115-234349](https://user-images.githubusercontent.com/3744056/212600641-b5605dbe-3d63-408b-bfef-6119b92f8684.png)
