### ISSUE TITLE
How to get second controller connected and working

### ISSUE THREAD

**Issue by Betonar** [darthcloud/BlueRetro#574]
### BlueRetro firmware version

1.8.2

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

willsconsolemodifications.co.uk

### System used

Sony PlayStation 1

### Bluetooth controller brand & name

Xbox Series (genuine) + PS3 (not sure of genuine)

### What is problem? (only list ONE problem per report)

Games dont recognise second controller.

I do have two SCPH-5552. Console 1 with PSD1+Xstation. Console 2: Xstation, DFO, X-reset. Two BlueRetro adapters on latest FW 1.8.2. Other modes on latest FW.

BlueRetro Setting (both adapters):
Present: Default Gamepad Only
Output1+2:
Advanced:
Global !
Sys: PSX, Multitab:No, Ing:Auto, Mem Card Bank: Bank1
Output1+2: Gamepad+Rumble

DS3 and Xbox controller works great whenever only controller is required for game. I can even connect second controller to Unoretro but no game is able to recongise that second controller is connected. For some reason I have to connect Xbox controller first and then DS3 (if i want to connect 2 gamepads)

This behavior is the same for both adapters and consoles and their combination. It worked in past. Im presume I made some sily error in setting. I hope someone can point me in the right direction.

### What did you expect to happen?

I expected that games will be able to use input from gamepad 2 as second valid simulated controller

**Comment by darthcloud** [comment]
You got a single port dongle. So you can't do traditional 2p with that.

A few games like Crash Team Racing support multitap on port one. So for those few games if you enable BlueRetro multitap mode then you can play multiplayer with a single dongle.
