### ISSUE TITLE
Gamecube 3rd Party controller issues.

### ISSUE THREAD

**Issue by Alex13mod** [darthcloud/BlueRetro#579]
### BlueRetro firmware version

1.8.2

### BlueRetro firmware specification

HW2

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

Internal install modkit

### Manufacturer

LaserBear

### System used

Nintendo GameCube

### Bluetooth controller brand & name

Keyboard 

### What is problem? (only list ONE problem per report)

Plugging the Retro Fighters in Port1 and using Bluetooth Keyboard. 
Keyboard stays in P1 and doesnt switch to P2 causing conflict with 3rd party controller.

### What did you expect to happen?

Keyboard synch to p2 and 3rd party wireless controller connected to P1 
2.4ghz controller
*Blade GC*

**Comment by Alex13mod** [comment]
Heres a video

**Comment by Sauced** [comment]
This is due to the Blade controller not triggering controller detection. 
A modification of the Retro Fighters receiver is required to trigger port detection. 
The shield on the controller connector needs to be connected to the ground connection on the receiver board.

**Comment by Alex13mod** [comment]
> This is due to the Blade controller not triggering controller detection. A modification of the Retro Fighters receiver is required to trigger port detection. The shield on the controller connector needs to be connected to the ground connection on the receiver board.

Thanks  for the update!!

**Comment by z3razerviper** [comment]
Just got my battler gc and it does not work correctly at all the analogue sticks keep getting stuck. You cant even make it off the first screen in zelda four swords.

**Comment by z3razerviper** [comment]
> This is due to the Blade controller not triggering controller detection. A modification of the Retro Fighters receiver is required to trigger port detection. The shield on the controller connector needs to be connected to the ground connection on the receiver board.

Do you have any links describing how to do the mod?

**Comment by Alex13mod** [comment]
By Laserbear
![20230130_073407](https://user-images.githubusercontent.com/72592730/215478401-bef4c20d-49a6-4bfd-b7c7-1833f3dfa0b1.jpg)
![20230130_073404](https://user-images.githubusercontent.com/72592730/215478405-f42d70db-e23d-491a-802e-9ff3db0a775f.jpg)

**Comment by z3razerviper** [comment]
Do you know if this will solve the wierd issues with sticks getting all confused.

**Comment by Sauced** [comment]
It should, you can test for sure by putting blue Retro into sleep at boot by holding reset. port 4 will be solid on and the blue retro board will not communicate on any ports. The communication is disabled when a controller is detected so it may be a control conflict.

**Comment by Alex13mod** [comment]
> Do you know if this will solve the wierd issues with sticks getting all confused.

Yes, The issues is port detection cause you probably using a a dongle and a Bluetooth device and both are conflicting with Port1

**Comment by Alex13mod** [comment]
> Do you know if this will solve the wierd issues with sticks getting all confused.

Here's a video of me using the mod:
[BLADE GC](https://twitter.com/alex13mod/status/1618349354963832832?t=B9S22B2tOBjwD66i9k77IQ&s=19)

**Comment by z3razerviper** [comment]
I will try it later however I am not using it with a Bluetooth device that's why I am a little worried. :(

**Comment by z3razerviper** [comment]
Ok so I tried the fix and I also tried disabling bluetooth on the blueretro no change I think i just have a bad controller :|

**Comment by Alex13mod** [comment]
> Ok so I tried the fix and I also tried disabling Bluetooth on the blueretro no change I think i just have a bad controller :

> Ok so I tried the fix and I also tried disabling Bluetooth on the blueretro no change I think i just have a bad controller :|

When you plug the dongle, does the Blue light switch to second port? Have you tried it on a diffrent system or PC?

**Comment by z3razerviper** [comment]
Yes it does light blue. I tried it on a pc but did not have any gamecube games to test it with since I have never setup dolphin. My primary use of this controller was only for gamecube.

**Comment by Sauced** [comment]
If it was still doing it with the blue retro disabled I would lean towards a bad controller/dongle over anything else. If a wired controller has the same issue then maybe it would be the board.
