### ISSUE TITLE
GuliKit Controller XW (KingKong 2) pair trace

### ISSUE THREAD

**Issue by rob-farrellrobotics** [darthcloud/BlueRetro#617]
### BlueRetro firmware version

NA

### BlueRetro firmware specification

HW2

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

Internal install DIY

### Manufacturer

me

### System used

Handheld

### Bluetooth controller brand & name

GuliKit Controller XW (KingKong 2)

### What is problem? (only list ONE problem per report)

New controller

### What did you expect to happen?

nothing, new controller

### Attach files like logs or Bluetooth traces here

[GuliKit Controller XW King Kong 2 pair trace.zip](https://github.com/darthcloud/BlueRetro/files/10774522/GuliKit.Controller.XW.King.Kong.2.pair.trace.zip)

**Comment by anherooftime69** [comment]
#146 ?

**Comment by darthcloud** [comment]
I don't really see anything wrong in the trace, look like standard Xinput.
What was the issue exactly?

You might want to try latest beta:
https://github.com/darthcloud/BlueRetro/actions/runs/6443343629

**Comment by darthcloud** [comment]
Feel free to reopen when you can provide requested info.
