### ISSUE TITLE
[GameCube BlueRetro Internal Adapter] Bluetooth earbuds disconnecting when powering on GC

### ISSUE THREAD

**Issue by sharkeylaser** [darthcloud/BlueRetro#634]
### BlueRetro firmware version

1.8.3

### BlueRetro firmware specification

HW2

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

Internal install modkit

### Manufacturer

Laser Bear Industries

### System used

Nintendo GameCube

### Bluetooth controller brand & name

[Earbuds] Tozo NC9

### What is problem? (only list ONE problem per report)

When powering on the GameCube with the internal BlueRetro adapter from Laser Bear Industries, my Bluetooth earbuds (paired and connected to my laptop) disconnect from my computer and refuse to reconnect until I put them back in their charging case and take them back out again. I've confirmed this happens every single time I power on the GameCube about two or three seconds after pressing the power button. They also do not reconnect until the GameCube is fully powered off. My earbuds are the Tozo NC9. Latest firmware, only paired an Exlene GameCube controller with the GameCube. Tried factory resetting, no change.

### What did you expect to happen?

The internal adapter should not disconnect my earbuds from the laptop.

**Comment by darthcloud** [comment]
There really nothing I can do, this is a bug with your earbuds. You should report that to them.

I got multiple Bluetooth audio device and none does that.
