### ISSUE TITLE
Sinilink APP Connecting automatically to Blueretro

### ISSUE THREAD

**Issue by Erick8x** [darthcloud/BlueRetro#679]
### BlueRetro firmware version

1.8.3

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter with multiple hardwired cord

### Manufacturer

RetroScaler

### System used

Nintendo 64

### Bluetooth controller brand & name

Nintendo Switch Pro Controller

### What is problem? (only list ONE problem per report)

When i power on my Nintendo 64 (And Wii, i have 2 RetroScaler 4-wired, one for N64 and one for GC), the BlueRetro automatically connects to my Xinyi Audio Amplifier (the name of bluetooth that this amp give is Sinilink App), so everytime i need to power off my amp, if not, always blueretro will connect Sinilink App to first port. Can i disable this auto connecting, like banning him to auto connect or something?

### What did you expect to happen?

I expect to not connect automatically my bluetooth amp to Blueretro, since this is not a controller.

**Comment by darthcloud** [comment]
Once you paired the controller once, it will remember BlueRetro, so you can change inquiry mode from auto to manual via config:

https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-BLE-Web-Config-User-Manual#22---global-config
