### ISSUE TITLE
Web Bluetooth API is not available - NO BROWSER SUPPORT

### ISSUE THREAD

**Issue by DoctorDan1986** [darthcloud/BlueRetro#681]
### BlueRetro firmware version

Unknown - cannot connect

### BlueRetro firmware specification

HW2

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

RetroTime

### System used

Nintendo 64

### What is problem? (only list ONE problem per report)

I have tried Safari, Chrome, and Firefox - not a single one of these browsers is able to connect to the Bluetooth Dongle to adjust settings.  I always get a "Web Bluetooth API is not available. Please make sure the "Experimental Web Platform features" flag is enabled." error that prevents me from doing anything.

Despite considerable Google-Fu, I have been unable to find out how to enable this setting on any browser, as all information seems to be woefully outdated or simply does not exist in a brand-new installation of the browsers attempted.  I'm pretty pissed off that the featureset of this dongle is closed to me.  Any advice before I simply return the damn thing for a refund would be appreciated.

### What did you expect to happen?

It to actually f'ing WORK?!
![Screen Shot 2023-05-07 at 4 28 34 AM](https://user-images.githubusercontent.com/8849311/236666592-877d1e86-15da-48e0-a829-cb858b5494a9.png)

**Comment by darthcloud** [comment]
I got a M2 pro mac and it work fine with Chrome out of the box just like Chrome on Windows or Android.

So you likely got a setting somewhere that is not default.
I'll take a look at my chrome flags when I'm back home.
