### ISSUE TITLE
DUAL JOYCONS

### ISSUE THREAD

**Issue by hermogenes12** [darthcloud/BlueRetro#684]
### BlueRetro firmware version

v1.7.3

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

I built with esp32

### System used

Sony PlayStation 1

### Bluetooth controller brand & name

JOYCONS 

### What is problem? (only list ONE problem per report)

I have a problem. I'm trying to connect the joy cons controllers to the PlayStation 2 to use as a single controller but the two controllers synchronize but I have no response when I press the buttons.

### What did you expect to happen?

I hope that someone with the same problem as mine appears to help me and it is very important that you manage to solve this problem.

**Comment by DS20815** [comment]
I'm having the same problem. My friend uses two Joycons with a 3D printed adapter as a single handed controller. I followed the pairing guide for the dual Joycon configuration but the right Joycon keeps disconnecting and does barely recognize button inputs. The left Joycon has also button mapping issues, despite correct setup via the web interface.

I'm using a blueretro Adapter for PSX/PS2 from Amazon (probably Bitfunx) with HW1 and updates it to FW 1.8.3

**Comment by darthcloud** [comment]
Due to bug #146 I wouldn't advice using two joycon as a single controller.

It's also complex to do the mapping:
https://github.com/darthcloud/BlueRetro/wiki/Controller-pairing-guide#63---dual-joycon-pairing-guide
