### ISSUE TITLE
Two identical controllers seem to both connect to same channel

### ISSUE THREAD

**Issue by vaderag** [darthcloud/BlueRetro#69]
I'm not 100% certain why this is happening but I have two identical 8bitdo controllers and initially thought one must be connecting to something else, but I've been round and turned off all Bluetooth I can find and now can only assume that they are both connecting on the same channel

Any ideas why this might be?

**Comment by darthcloud** [comment]
Do they work properly with BlueRetro one at a time?

Can you get the debug logs: https://github.com/darthcloud/BlueRetro/wiki/Getting-BlueRetro-debug-logs-via-Serial-port-Windows-10

**Comment by vaderag** [comment]
Yep, one at a time is good. Will check the logs when I have a moment

**Comment by vaderag** [comment]
Okay, so I've worked out what it is, and there is an issue but not the same as I thought

The controllers in the pic are all connected
 Notice how there are two ones and one 3. Turns out that 8bitdo #2 is connected but not receiving(?) the correct status assignment. So it always shows as P1
I've tried connecting in all positions and irrespective what player it's assigned to it shows #1
Also connection mode doesn't make a difference (except to the button layout), still shows as P1 in Switch or Xinput modes

![IMG_20210919_103432.jpg](https://user-images.githubusercontent.com/17175988/133922594-0d83b798-e31b-439e-990c-6558f37d8324.jpg)

**Comment by darthcloud** [comment]
This is likely just a cosmetic LED issue, you should have one being P1 and the other being P2

**Comment by vaderag** [comment]
> This is likely just a cosmetic LED issue, you should have one being P1 and the other being P2

Oh it is just cosmetic - but it's quite confusing given other controllers seem to connect with the correct # designation.

**Comment by darthcloud** [comment]
Closing this, 8bitdo ctrl need to be used in Xinput mode which provides no player LED indicator.

If official SW ctrl where also concerned by this issue it's likely  a manifestation of issue #146
