### ISSUE TITLE
Gamepad esp32

### ISSUE THREAD

**Issue by Radionews** [darthcloud/BlueRetro#767]
### BlueRetro firmware version

1.8.4

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

Internal install DIY

### Manufacturer

me

### System used

Nintendo Famicom NES

### Bluetooth controller brand & name

ESP32 

### What is problem? (only list ONE problem per report)

new protocol

### What did you expect to happen?

I built my own joystick on esp32. I'm trying to connect

### Attach files like logs or Bluetooth traces here

[blueesp32.zip](https://github.com/darthcloud/BlueRetro/files/12531294/blueesp32.zip)

**Comment by darthcloud** [comment]
I do not provide support for custom DIY BT pad.

Other people made custom DIY pad and didn't require change to be made on the BlueRetro side.
