### ISSUE TITLE
Request: mapping source/dest button naming

### ISSUE THREAD

**Issue by GizmoTheGreen** [darthcloud/BlueRetro#77]
on the web interface on the button mapping page, you could have one dropdown for Source and one for destination.
user could then choose the right controller (i.e Wii u pro -> n64) and the page would rename the "blueretro" button names to the correct ones, so you don't need to sit with Reference sheet every time...

it's just for convenience, and I think it can all be done on the web page server side, no need to change in FW

If I am mistaken I am sorry.

**Comment by GizmoTheGreen** [comment]
will switch n64 controller get it's own labelings?

**Comment by darthcloud** [comment]
Just select the existing N64 labels

**Comment by GizmoTheGreen** [comment]
oh ok. because I thought of the swithc n64 controller as a switch pro controller with weird mapping I somehow assumed it needed it's own labels. 

my bad!

**Comment by darthcloud** [comment]
Yes but BlueRetro take care of the weirdness ;)
