### ISSUE TITLE
8BitDo Retro Mechanical Keyboard not working on GameCube!

### ISSUE THREAD

**Issue by ABOhiccups** [darthcloud/BlueRetro#785]
### BlueRetro firmware version

v1.8.4

### BlueRetro firmware specification

HW2

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

Internal install modkit

### Manufacturer

Laser Bear Industries

### System used

Nintendo GameCube

### Bluetooth controller brand & name

8BitDo Retro Mechanical Keyboard

### What is problem? (only list ONE problem per report)

8BitDo Retro Mechanical Keyboard in Bluetooth Mode is not typing on Phantasy Star Online Episode I & II.

### What did you expect to happen?

Use 8BitDo Retro Mechanical Keyboard in Bluetooth Mode as alternative to Japanese GameCube Keyboard Controller.

**Comment by darthcloud** [comment]
Should work in latest beta:

https://github.com/darthcloud/BlueRetro/actions/runs/7081676820

**Comment by darthcloud** [comment]
Fix is now in v1.9.1
