### ISSUE TITLE
Disconnects when strong rumble occurs

### ISSUE THREAD

**Issue by backdash756** [darthcloud/BlueRetro#802]
### BlueRetro firmware version

v1.8.4

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter with multiple hardwired cord

### Manufacturer

Jerilla

### System used

SEGA Dreamcast

### Bluetooth controller brand & name

PS4 & Xbox One S

### What is problem? (only list ONE problem per report)

If there is strong vibration, the controller disconnects. It feels as if the vibration lasts too long and then it becomes disconnected. If you turn off the vibration, there is no disconnect at the points in the game where it happens.

### What did you expect to happen?

The controller should remain connected, even with strong vibration.

**Comment by darthcloud** [comment]
Dreamcast rumble is highly experimental I still need to reverse engineer it properly as noted in this earlier bug #5 .

Closing this one as duplicate.
