### ISSUE TITLE
Remapping one controller affects mappings for all controllers

### ISSUE THREAD

**Issue by IceBlueLugia** [darthcloud/BlueRetro#805]
### BlueRetro firmware version

1.8.4 HW1

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

External adapter with multiple hardwired cord

### Manufacturer

GrechTech/RetroRosetta

### System used

Nintendo Wii Extension

### Bluetooth controller brand & name

Switch Pro, all 4 Switch NSO, PS4

### What is problem? (only list ONE problem per report)

When using the button remapping tool, changing the mapping for any controller causes the mapping for everything else to change as well. I am using Bluefy browser on iOS, but the issue happens on other browsers and devices I tested. I connect the Switch NES NSO controller to my Wii, and A and B are recognized as B and Y; when I select the source as Switch NES and destination as classic controller pro, I then change the mappings. However, this now causes the mappings for every other controller to be wrong. SNES, N64, and Genesis NSO controllers, as well as Switch Pro and PS4 controllers all now have a shifted button layout based on this change. The problem is, even if I go into these controller settings to change them (by selecting Switch SNES as source for example), now the NES one is messed up again. I can’t really use the default settings as it makes some of these controllers essentially unusable. Even the default SNES one has the bumpers and triggers reversed. I have tried editing one device at a time, then saving, then power cycling, then repeating. I have tried editing everything at once then saving. I have tried multiple combinations of the two and nothing has worked. Is there a way to get specific controllers to just be assigned specific mappings?

I even tried this on a different adapter entirely (a 4 port gamecube one I bought off AliExpress) and the same issue happened

### What did you expect to happen?

I expected that when I edit the mappings for an individual controller type, only that mapping gets changed

### Attach files like logs or Bluetooth traces here

this is the log from when I edited them all at once

Reading App version…
Reading Api version…
Requesting Bluetooth Device...
Connecting to GATT Server...
Getting BlueRetro Service...
ABI version: 2
Init Cfg DOM..
Get Global Config CHRC...
Reading Global Config...
Global Config size: 4
Get Output 0 CTRL CHRC...
Set Output 0 on CTRL chrc...
Get Output 0 DATA CHRC...
Reading Output 0 Config...
Output 0 Config size: 2
Get Input 0 Config CHRC...
Set Input Ctrl CHRC... O Reading Input Data CHRC...
Got Input Data 512
Got Input Data 115 115
Set Input Ctrl CHRC... 512
Reading Input Data CHRC..
Got Input Data 411
Got Input Data 115 0
Input 0 Config size: 2051
Input 0 Config size: 2051
Loading Mapping Found: 115 nbMapping: 115 cfg:
115
Get Input 2 Config CHRC...
Set Input Ctrl CHRC... 0
Get Input 1 Config CHRC...
Reading Input Data CHRC...
Got Input Data 512
Got Input Data 115 115
Set Input Ctrl CHRC... 512
Set Input CtrI CHRC... 0
Reading Input Data CHRC...
Reading Input Data CHRC...
Got Input Data 411
Got Input Data 115 0
Input 2 Config size: 2051
Input 2 Config size: 2051
Loading Mapping Found: 115 nbMapping: 115 cfg:
115
Got Input Data 411
Got Input Data 0 0
Input 1 Config size: 2051
Input 1 Config size: 2051
Loading Mapping Found: 0 nbMapping: 0 cfg: 0
Get Input 0 Config CHRC...
Set Input Ctrl CHRC... 0
Reading Input Data CHRC...
Got Input Data 512
Got Input Data 115 115
Set Input Ctrl CHRC... 512
Reading Input Data CHRC...
Got Input Data 411
Got Input Data 115 0
Input 0 Config size: 2051
Input 0 Config size: 2051
Loading Mapping Found: 115 nbMapping: 115 cfg:
115
Get Input 1 Config CHRC...
Set Input Ctrl CHRC... 0
Reading Input Data CHRC...
Got Input Data 512
Got Input Data 115 115
Set Input Ctr\ CHRC... 512
Reading Input Data CHRC...
Got Input Data 411
Got Input Data 115 0
Input 1 Config size: 2051
Input 1 Config size: 2051
Loading Mapping Found: 115 nbMapping: 115 cfg:
115
Get Input 0 Config CHRC...
Set Input Ctrl CHRC... 0
Reading Input Data CHRC...
Got Input Data 512
Got Input Data 115 115
Set Input Ctrl CHRC... 512
Reading Input Data CHRC...
Got Input Data 411
Got Input Data 115 0
Input 0 Config size: 2051
Input 0 Config size: 2051
Loading Mapping Found: 115 Mapping: 115 cfg:
115
Get Input 1 Config CHRC...
Set Input Ctrl CHRC... 0
Reading Input Data CHRC..
Got Input Data 512
Got Input Data 115 115
Set Input Ctrl CHRC... 512
Reading Input Data CHRC...
Got Input Data 411
Got Input Data 115 0
Input 1 Config size: 2051
Input 1 Config size: 2051
Loading Mapping Found: 115 Mapping: 115 cfg:
115
Get Input 0 Config CHRC...
Set Input Ctrl CHRC... 0
Reading Input Data CHRC...
Got Input Data 512
Got Input Data 115 115
Set Input Ctrl CHRC... 512
Reading Input Data CHRC...
Got Input Data 411
Got Input Data 115 0
Input 0 Config size: 2051
Input 0 Config size: 2051
Loading Mapping Found: 115 nbMapping: 115 cfg:
115
Set Input Ctrl CHRC... 0
Writing Input Data CHRC...
Input Data Written
Set Input Ctrl CHRC... 512
Writing Input Data CHRC..
Input Data Written
Input 0 Config saved
> Bluetooth Device disconnected

**Comment by darthcloud** [comment]
There is **ONE** mapping, so it affects everything.

Those are only labels to help you make a mapping, it's not a config selection.

So this is expected.

To have per system config you can use the gameid feature.
https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-BLE-Web-Config-User-Manual#21---config-selection
