### ISSUE TITLE
[PS2] Сharacter switches to walking

### ISSUE THREAD

**Issue by DOOTGUY** [darthcloud/BlueRetro#806]
### BlueRetro firmware version

1.9

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

RetroScaler

### System used

Sony PlayStation 2

### Bluetooth controller brand & name

Original Sony Dualshock 4 (2 of them) & Switch Pro Controller

### What is problem? (only list ONE problem per report)

Сharacter switches to walking when left stick placed somewhere diagonally. Tested via 3 controllers

### What did you expect to happen?

I expected the controller to work normally

**Comment by darthcloud** [comment]
Maybe tell me the games name?

**Comment by DOOTGUY** [comment]
I tested multiple games (Rayman 3, Asterix at Yhe olimpic games, Kung fu Panda) and they all have same issue, somewhere more, somewhere less, but this problem appears after update

**Comment by darthcloud** [comment]
Can you try this version
[v1.9.1-beta-1-gf94313f_hw1.zip](https://github.com/darthcloud/BlueRetro/files/13048815/v1.9.1-beta-1-gf94313f_hw1.zip)

**Comment by DOOTGUY** [comment]
Same problem

**Comment by darthcloud** [comment]
Fix is now in v1.9.1

Make sure your adapter display version v1.9.1 in the web after updating.

I tested myself with PS4.ctrl and had not slowdown in diagonal in kungfu panda
