### ISSUE TITLE
Same brand Blueretro, one will cause memcard Pro errors, and the other will not

### ISSUE THREAD

**Issue by SoukinOKATU** [darthcloud/BlueRetro#812]
### BlueRetro firmware version

1.9

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

External adapter with detachable cord

### Manufacturer

RetroScaler

### System used

Sony PlayStation 1

### Bluetooth controller brand & name

PS3 dualshock 3

### What is problem? (only list ONE problem per report)

The same receiver(RetroScaler BlueRetro Wireless Game Controllers Converter Adapter For PS1 PS2 ）, with a transparent shell, can cause memcard pro read and write errors, while a black shell will not

### What did you expect to happen?

Unable to read/write archive, such as'Akumajou Dracula X '，It will display a bad memory card（Japanese:不良）or 'no card'，Occasionally, SAVE files are displayed, but there may be read errors.
Strangely, with another black shell receiver (with the same model and firmware version), everything returned to normal

**Comment by darthcloud** [comment]
If both use same firmware version then this is a hardware.

Reach out to your hardware vendor. ie RetroScaler.

Nothing I can do on software side.
