### ISSUE TITLE
Help, I turned it useless

### ISSUE THREAD

**Issue by patschgoo** [darthcloud/BlueRetro#814]
### BlueRetro firmware version

dbg_qemu

### BlueRetro firmware specification

HW2

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

External adapter with detachable cord

### Manufacturer

BitFunx

### System used

Sony PlayStation 2

### What is problem? (only list ONE problem per report)

I accidentaly updated my device with dbg_qemu instead of what I probably should have used BlueRetro_playstation v1.9_hw1 and now I don't know any way to change it, because it doesn't go into sync mode anymore

### What did you expect to happen?

To update it with the right software, I missclicked and have no way to change it back and can't fand anything how to do it and for some reason couldn't cancel the update, i clicked multiple times please help me if there is a way

**Comment by darthcloud** [comment]
Update with USB
https://github.com/darthcloud/BlueRetro/wiki/Flashing-firmware-Windows-10
