### ISSUE TITLE
Support for SN30 Pro+ and 8Bitdo Arcade Stick broken

### ISSUE THREAD

**Issue by GeneralMorden** [darthcloud/BlueRetro#857]
### BlueRetro firmware version

1.9.1

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

Humble Bazooka and Laserbear

### System used

SNK NeoGeo AES

### Bluetooth controller brand & name

SN30 Pro+ and Arcade Stick 8Bitdo

### What is problem? (only list ONE problem per report)

In X-Input SN30 Pro+ and Arcade Stick are not support since 1.9.1. Mapping is broken.

### What did you expect to happen?

Please fix this. Is the a place i can download 1.9 firmware?

**Comment by darthcloud** [comment]
I re-added v1.9 on https://darthcloud.itch.io/blueretro for now.

**Comment by GeneralMorden** [comment]
Thank you!!

**Comment by darthcloud** [comment]
Can you try this beta and see if the mapping is right:
[v1.9.2-beta-3-g4135621_hw1.zip](https://github.com/darthcloud/BlueRetro/files/13812810/v1.9.2-beta-3-g4135621_hw1.zip)
[v1.9.2-beta-3-g4135621_hw2.zip](https://github.com/darthcloud/BlueRetro/files/13812811/v1.9.2-beta-3-g4135621_hw2.zip)

**Comment by GeneralMorden** [comment]
Yes i will try.

02.01.2024 19:08:00 Jacques Gagnon ***@***.***>:

**Comment by GeneralMorden** [comment]
Tested the beta per 8Bitdo Arcade Stick on NeoBT (MVS) and SN30 Pro on Laserbears Game Cube device. Now, everything seems to Work correctly 👍

07.01.2024 20:11:27 Philipp Klose ***@***.***>:

**Comment by darthcloud** [comment]
[Fixed in v1.9.2](https://github.com/darthcloud/BlueRetro/releases/tag/v1.9.2)
