### ISSUE TITLE
DC Keyboard ghost keystrokes in certain games.

### ISSUE THREAD

**Issue by polyv0x** [darthcloud/BlueRetro#891]
### BlueRetro firmware version

1.9.1

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

Internal install DIY

### Manufacturer

Espressif

### System used

SEGA Dreamcast

### Bluetooth controller brand & name

Filco Majestouch Minila Air

### What is problem? (only list ONE problem per report)

PSO, ToTD seem to have a lot of "debounce" ghost keystrokes when typing fast. 

For example if I type asdf 5 times real quick, it will look like: "asdf asadf asdfa asdf asdfd"  (letters are randomly doubled, making typing correctly with higher speeds impossible)

Noticed that Quake 3 Arena has no issues whatsoever when typing fast in the chat. 

Same keyboard functions just fine on other hardware when typing fast.

### What did you expect to happen?

Accurate typing just like in Quake 3.

**Comment by darthcloud** [comment]
Can you try this beta firmware:
https://github.com/darthcloud/BlueRetro/actions/runs/8762666480

I think it should fix it.

**Comment by polyv0x** [comment]
Awesome work, this indeed fixed it :)

**Comment by darthcloud** [comment]
Thanks for testing I will close once officially released

**Comment by darthcloud** [comment]
Fixed in v24.04
