### ISSUE TITLE
logical_min should be a singed value

### ISSUE THREAD

**Issue by tpunix** [darthcloud/BlueRetro#893]
### BlueRetro firmware version

latest

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

diy

### System used

SEGA Saturn

### What is problem? (only list ONE problem per report)

file main/adapter/hid_parser.c  line 302:
hid_stack[hid_stack_idx].logical_min = *desc++;
logical_min will get a unsigned byte value.

### What did you expect to happen?

logical_min should be a signed value:
logical_min = *(int8t *)desc++;

**Comment by darthcloud** [comment]
[Fixed in v1.9.2](https://github.com/darthcloud/BlueRetro/releases/tag/v1.9.2)
