### ISSUE TITLE
N64 Rumble stop to work

### ISSUE THREAD

**Issue by KITTRider86** [darthcloud/BlueRetro#911]
### BlueRetro firmware version

1.9.1

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

RetroScaler

### System used

Nintendo 64

### Bluetooth controller brand & name

NSO N64 controller

### What is problem? (only list ONE problem per report)

The vibration stops working occasionally in Majora Mask, even if I press the home button to switch between the controller pak and the rumble, it no longer vibrates. I unplug the receiver and plug it back in, and everything works again. Defective receiver?

### What did you expect to happen?

Rumble don't stop working

**Comment by drackybrok** [comment]
Have you tried the latest firmware? I believe this issue was fixed in the newest firmware 1.9.2

**Comment by darthcloud** [comment]
Can you test this beta, This completely rework the rumble support
I think it might fix that issue aswell.

https://github.com/darthcloud/BlueRetro/actions/runs/9286878322

**Comment by darthcloud** [comment]
Fixed in v24.10:
https://github.com/darthcloud/BlueRetro/releases/tag/v24.10
