### ISSUE TITLE
8BitDo N64 Modkit, unable to press simultaneously C-Up+C-Down and C-Left+C-Right

### ISSUE THREAD

**Issue by Daneeall** [darthcloud/BlueRetro#912]
### BlueRetro firmware version

1.9.1

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

Retro Scaler

### System used

Nintendo 64

### Bluetooth controller brand & name

8BitDo N64 Modkit

### What is problem? (only list ONE problem per report)

Unable to press simultaniously C-Up+C-Down and C-Left+C-Right

### What did you expect to happen?

It should be two logical 1 instead of zeros at the same time. So there is no way to load game from save in Doom 64, cuz you need to simultaneously press C-Left+C-Right.
C-Up+C-Down also doesn't work.

**Comment by darthcloud** [comment]
Thats a limitation of the controller itself in d-input mode.

The C stick is exposed only as the right joystick which do not allow for both opposing direction simultaneously.

A workaround would be to map another buttons as one of the c direction.

Or use Switch mode, but the mapping will be wrong on reconnection. Only on initial connection the mapping will be right.
