### ISSUE TITLE
Gamecube digital ‘click’ L and R Triggers

### ISSUE THREAD

**Issue by haydnkilyan** [darthcloud/BlueRetro#930]
### BlueRetro firmware version

v1.9.2

### BlueRetro firmware specification

HW2

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

Internal install modkit

### Manufacturer

Laserbear

### System used

Nintendo GameCube

### Bluetooth controller brand & name

8Bitdo Pro 2

### What is problem? (only list ONE problem per report)

I set the L2 / R2 trigger threshold to act as the digital L/R trigger presses, when the threshold of 95% is reached. I have some controller test software to check and it works perfectly when one controller is connected. When I connect a second controller, the digital ‘click’ no longer registers on EITHER controller……. This was not a problem on the v1.8.3 firmware…. Though rumble does not seem to work on 8bitdo Pro 2 using this firmware…. Was going to roll back to v1.8.2 - but it is no longer available 

### What did you expect to happen?

The digital clicks to register at 95%

**Comment by haydnkilyan** [comment]
What's sad is that I think v1.8.2 work perfectly for my set up - and now I cannot get it back!

**Comment by haydnkilyan** [comment]
Just remembered, on v1.8.3 you have to set the controllers to have 'rumble' manually - so all works fine on 1.8.3...... but still issue on 1.9.X

**Comment by darthcloud** [comment]
What is the 2nd controller brand you are issue? Both are 8bitdo Pro 2? Are they connected in Xinput mode?

All the old FW are in the release section:
https://github.com/darthcloud/BlueRetro/releases/tag/v1.8.2

**Comment by haydnkilyan** [comment]
Hello! Thank you for getting back to me. Yes both controllers are 8Bitdo Pro 2s set to X input

**Comment by darthcloud** [comment]
Does applying the GC Merge trigger preset help?

See animated gif in wiki
https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-BLE-Web-Config-User-Manual#33---example-preset-load

**Comment by darthcloud** [comment]
This beta should fix it there was indeed a problem with trigger in multiplayer:
https://github.com/darthcloud/BlueRetro/actions/runs/8680779369

**Comment by darthcloud** [comment]
Fixed in v24.04
