### ISSUE TITLE
3rd party wii u pro controller 

### ISSUE THREAD

**Issue by ZeleiAttila** [darthcloud/BlueRetro#950]
### BlueRetro firmware version

1.9.2

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

External adapter dongle (1 port only)

### Manufacturer

unknown

### System used

Sony PlayStation 1

### Bluetooth controller brand & name

wii u pro

### What is problem? (only list ONE problem per report)

I'm trying to use my 3rd party Wii U Pro Controller with a PS1. I go through all the pairing steps, and it seems successful. The BlueRetro dongle stops flashing and the first LED on the controller remains lit, indicating it's connected to the first slot. However, after this, nothing happens. Pressing any button does nothing; for instance, I can't navigate the game menu. 

 I've tried using this BlueRetro with a regular Wii motion controller, and it worked fine.

Can you help? How can I assist in sending logs to find out what the problem might be?

### What did you expect to happen?

My expectation is that it should work.

**Comment by darthcloud** [comment]
If you can make the controller functional in Windows you could make a trace of it:
https://github.com/darthcloud/BlueRetro/wiki/Bluetooth-HCI-trace-with-Win10

But I don't think Wii controller can work in Windows without using some sort of 3rd party driver. I never done so myself.

Best would for me to have one, where that controller come from?

**Comment by darthcloud** [comment]
Feel free to reopen if you got more info
