### ISSUE TITLE
Stadia controller sends additional button presses on N64

### ISSUE THREAD

**Issue by asweintraub** [darthcloud/BlueRetro#958]
### BlueRetro firmware version

v1.9.1_hw1_universal and v24.04_beta_universal_hw1

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

External adapter with detachable cord

### Manufacturer

blue-retro.com

### System used

Nintendo 64

### Bluetooth controller brand & name

Google Stadia

### What is problem? (only list ONE problem per report)

Using the left trigger on the Stadia controller activates both C-up and Z in N64 games. When pressing the trigger very slightly, C-up activates immediately, but Z has slightly more of a dead zone before activating. The right trigger on the Stadia controller only activates Z on the N64, which is what I would expect.

It seems as if the left trigger controller axis could be getting mapped to the RY axis (in addition to the Z button), but I haven't confirmed this.

### What did you expect to happen?

The left trigger on the Stadia controller only activates Z and doesn't also press C-up.

**Comment by asweintraub** [comment]
From the duped bug:

Pressing the menu button on the Stadia controller activates both the Start button and C-right on the N64 (confirmed with a controller test rom).

**Comment by darthcloud** [comment]
Please try this beta:
https://github.com/darthcloud/BlueRetro/actions/runs/8757581399

I did see the L button issue in my n64 rom test but not the start button one.

Let me know if it fix one or both of the issues.

**Comment by asweintraub** [comment]
Yup, just tried this out and all the buttons work properly now. Thank you for the quick fix!

**Comment by darthcloud** [comment]
I handle the closing :P

**Comment by asweintraub** [comment]
Oops, sorry about that!

**Comment by darthcloud** [comment]
Fixed in v24.04
