### ISSUE TITLE
Stadia controller menu button sends both Start and C-right on N64

### ISSUE THREAD

**Issue by asweintraub** [darthcloud/BlueRetro#959]
### BlueRetro firmware version

v1.9.1_hw1_universal and v24.04_beta_universal_hw1

### BlueRetro firmware specification

HW1

### BlueRetro firmware variant

Universal

### BlueRetro hardware type

External adapter with detachable cord

### Manufacturer

blue-retro.com/aliexpress

### System used

Nintendo 64

### Bluetooth controller brand & name

Google Stadia

### What is problem? (only list ONE problem per report)

Pressing the menu button on the Stadia controller activates both the Start button and C-right on the N64 (confirmed with a controller test rom).

### What did you expect to happen?

The menu button only activates Start.

This is similar to https://github.com/darthcloud/BlueRetro/issues/958, so feel free to mark it as a duplicate if that's appropriate.

**Comment by darthcloud** [comment]
Let mark this one dup of #958 to make tracking easier.
