### ISSUE TITLE
Integer Overflow on analog sticks

### ISSUE THREAD

**Issue by dur75945** [darthcloud/BlueRetro#97]
I found this out while try to trouble shoot an issue that I found when trying to reduce the sensitivity of the analog stick is the web config, but they just ended up fixing themselves somehow. regardless when I was trouble shooting I saw that if the sensitivity cranked up really high, like around 150%, something along the lines of an overflow happens with the stick values reading as just outside of the deadzone.

![image](https://user-images.githubusercontent.com/85606597/143317401-397bc62b-26d7-41dc-9943-99f645d71fe3.png)
I just made a sketch is paint, inner circle is the deadzone, red is the xbox stick position, blue is what the game is reading

**Comment by darthcloud** [comment]
Can you confirm you observe this on GameCube? Thanks
