### ISSUE TITLE
[24.04] Reset Power-Off Doesn't Trigger As Expected

### ISSUE THREAD

**Issue by AskaLangly** [darthcloud/BlueRetro#986]
### BlueRetro firmware version

24.04

### BlueRetro firmware specification

HW2

### BlueRetro firmware variant

System specific

### BlueRetro hardware type

Internal install modkit

### Manufacturer

LaserBear

### System used

Nintendo GameCube

### Bluetooth controller brand & name

8bitdo Ultimate BT

### What is problem? (only list ONE problem per report)

The "double-tap reset to turn off the system" functionality is more miss than hit. If anything, when it does work, I notice that when I start to double-press reset a second time, it will turn off more often if tapped the right timing. 

### What did you expect to happen?

Expected the system to turn off via relay after the double-tap every time, without having the console reset when the command is done proper.

**Comment by darthcloud** [comment]
It work this way, you just need to get use to it.

I not ideal but I the best it can be.
